GoedertWeb.UI/Models/DadosDocumentos.cs
namespace GoedertWeb.UI.Models
{
    public class DadosDocumentos
    {
        public string id_documento { get; set; }
        public string id_pessoa { get; set; }
        public string id_tipo_documento { get; set; }
        public string numero { get; set; }
        public string emissor { get; set; }
        public string dt_validade { get; set; }
        public string dt_emissao { get; set; }
        public string descricao { get; set; }
    }
}

GoedertWeb.UI/Models/DadosPessoas.cs
using System.Collections.Generic;

namespace GoedertWeb.UI.Models
{
    public class DadosPessoas
    {
        public DadosPessoas()
        {
            dadosDocumentos = new List<DadosDocumentos>();
        }

        public string id_pessoa { get; set; }
        public string id_tipo_pessoa { get; set; }
        public string nome { get; set; }
        public string sexo { get; set; }
        public byte[] foto { get; set; }
        public string dt_ini_val { get; set; }
        public string dt_fim_val { get; set; }
        public string descricao { get; set; }
        public string foto_string { get; set; }
        public List<DadosDocumentos> dadosDocumentos { get; set; }
    }
}

GoedertWeb.UI/Controllers/CadastroController.cs
using GoedertWeb.UI.Models;
using System.Web.Configuration;
using System.Web.Mvc;

namespace GoedertWeb.UI.Controllers
{
    public class CadastroController : Controller
    {
        // GET: Cadastro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TelaCrud(string acao)
        {
            ViewBag.IND_ACAO = acao;

            DadosPessoas model = new DadosPessoas();

            model.id_tipo_pessoa = "";
            model.sexo = "";

            return PartialView("_partialCrud", model);
        }

        public ActionResult WebCam(string acao)
        {
            ViewBag.ACAO = acao;

            DadosPessoas model = new DadosPessoas();

            return PartialView("_webCam", model);
        }
    }
}

GoedertWeb.UI/Controllers/ConsultaController.cs
using GoedertWeb.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GoedertWeb.UI.Controllers
{
    public class ConsultaController : Controller
    {        
        // GET: Consulta
        public ActionResult Index()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult TelaConsulta()
        {
            return PartialView("Index");
        }

        [HttpPost]
        public ActionResult ResumoConsulta(List<DadosPessoas> model, string viewCadastro = "N", string tipoPesquisa = "")
        {
            ViewBag.VIEW_CADASTRO = viewCadastro;
            ViewBag.TIPO_PESQUISA = tipoPesquisa;

            model = model ?? new List<DadosPessoas>();            

            if (model.Count > 0)
            {
                foreach (var dadosPessoa in model)
                {                    
                    if (dadosPessoa.foto != null)
                    {
                        var imagem = Convert.ToBase64String(dadosPessoa.foto);

                        if (imagem.Equals("QEA=") || imagem.Equals("AA==") || String.IsNullOrEmpty(imagem))
                        {
                            dadosPessoa.foto_string = null;
                            dadosPessoa.foto = null;
                        }
                        else
                        {
                            dadosPessoa.foto_string = String.Format("data:image/png;base64,{0}", imagem);
                            dadosPessoa.foto = null;
                        }
                    }

                    if (!String.IsNullOrEmpty(dadosPessoa.dt_ini_val))
                    {
                        dadosPessoa.dt_ini_val = dadosPessoa.dt_ini_val.Replace("T00:00:00", "");
                        string[] dt_ini_val = dadosPessoa.dt_ini_val.Split('-');
                        dadosPessoa.dt_ini_val = dt_ini_val[2] + '/' + dt_ini_val[1] + '/' + dt_ini_val[0];
                    }

                    if (!String.IsNullOrEmpty(dadosPessoa.dt_fim_val))
                    {
                        dadosPessoa.dt_fim_val = dadosPessoa.dt_fim_val.Replace("T00:00:00", "");
                        string[] dt_fim_val = dadosPessoa.dt_fim_val.Split('-');
                        dadosPessoa.dt_fim_val = dt_fim_val[2] + '/' + dt_fim_val[1] + '/' + dt_fim_val[0];
                    }

                    if (dadosPessoa.dadosDocumentos.Count > 0)
                    {
                        foreach (var dadosDocumento in dadosPessoa.dadosDocumentos)
                        {
                            if (!String.IsNullOrEmpty(dadosDocumento.numero) && !String.IsNullOrEmpty(dadosDocumento.descricao))
                            {
                                dadosDocumento.descricao += " " + dadosDocumento.numero;
                            }
                            else
                            {
                                dadosDocumento.descricao = "";
                                dadosDocumento.numero = "";
                            }

                            if (!String.IsNullOrEmpty(dadosDocumento.dt_emissao))
                            {
                                dadosDocumento.dt_emissao = dadosDocumento.dt_emissao.Replace("T00:00:00", "");
                                string[] dt_emissao = dadosDocumento.dt_emissao.Split('-');
                                dadosDocumento.dt_emissao = dt_emissao[2] + '/' + dt_emissao[1] + '/' + dt_emissao[0];
                            }

                            if (!String.IsNullOrEmpty(dadosDocumento.dt_validade))
                            {
                                dadosDocumento.dt_validade = dadosDocumento.dt_validade.Replace("T00:00:00", "");
                                string[] dt_validade = dadosDocumento.dt_validade.Split('-');
                                dadosDocumento.dt_validade = dt_validade[2] + '/' + dt_validade[1] + '/' + dt_validade[0];
                            }
                        }
                    }
                }
            }

           return PartialView(model);
        }

        [HttpPost]
        public ActionResult TelaCrud(string acao, string idPessoa, List<DadosPessoas> dadosPessoas)
        {
            ViewBag.IND_ACAO = acao;

            var model = dadosPessoas.Where(t => t.id_pessoa == idPessoa).SingleOrDefault();

            return PartialView("_partialCrud", model);
        }
        
        [HttpPost]
        public ActionResult WebCam(string acao, string idPessoa, List<DadosPessoas> dadosPessoas, string viewCadastro = "N", string tipoPesquisa = "")
        {
            ViewBag.ACAO = acao;
            ViewBag.VIEW_CADASTRO = viewCadastro;
            ViewBag.TIPO_PESQUISA = tipoPesquisa;

            var model = dadosPessoas.Where(t => t.id_pessoa == idPessoa).SingleOrDefault();

            return PartialView("_webCam", model);
        } 
    }
}

GoedertWeb.UI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace GoedertWeb.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

GoedertWeb.UI/Views/Cadastro/Index.cshtml
<div class="jumbotron">
    <div class="row">
        <h2>
            <label class="label label-success">
                <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                Cadastrar
            </label>
        </h2>
    </div>
</div>

<div id="divBtnGravarNovaPessoa" class="row" style="display:none;">
    <div class="col-md-12 text-center">
        <button type="button" id="btnGravarNovaPessoa" class="btn btn-success btn-lg">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            Cadastrar outra pessoa?
        </button>
    </div>
</div>

<div id="divCadastro" style="display:none;">
    <div class="row">
        <div class="col-md-12">
            <div id="divCrud"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="text-center">
                <div class="btn-group">
                    <button type="button" id="btnGravarForm" onclick="GravarForm();" class="btn btn-success btn-lg" disabled="disabled">
                        <span class="glyphicon glyphicon-floppy-open" aria-hidden="true"></span>
                        Gravar Dados
                    </button>
                    <button type="button" onclick="LimparForm();" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
                        Limpar Dados
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="divWebCam" style="display:none;">
</div>

<div id="divResumoConsulta" style="display:none;">
</div>

@section scripts{

<script>

    $(document).ready(function () {

        function CarregaTelaCrud() {
            $.ajax({
                url: '@Url.Action("TelaCrud", "Cadastro")',
                method: 'POST',
                dataType: 'html',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify({
                    'acao': 'I'
                })
            }).done(function (data, status) {
                $('#divCrud').html(data);
                $('#formCamera').show();
                $('#divCadastro').show();
                $('#sexo option[value=""]').show();
            }).fail(function (data, status) {
                $.notify('Erro ao carregar a tela de crud para inclusão de novas pessoas...', { clickToHide: true, autoHide: false });
            });
        }
        
        CarregaTelaCrud();

    });

    function LimparForm() {
        $('#formDadosPessoa').trigger("reset");
        $('#btnGravarForm').prop("disabled", true);
    }

    function GravarForm() {
            var formPessoa = $('#formDadosPessoa').serializeArray();
            var formPessoaJson = { foto_string: $('#fotoString').val() };
            $.each(formPessoa,
                function (i, v) {
                    formPessoaJson[v.name] = v.value;
                });

            $.ajax({
                url: '@Session["WEB_API"].ToString()/api/pessoas/cadastrarPessoas',
                method: 'POST',
                dataType: 'json',
                data: formPessoaJson
            }).done(function (data, status) {
                if (data.mensagemRetorno.includes('sucesso'))
                {
                    $.notify(data.mensagemRetorno, { className: 'success', clickToHide: true, autoHide: false });
                    GetPessoa(data.idPessoa);
                }
                else
                {
                    $.notify(data.mensagemRetorno, { clickToHide: true, autoHide: false });
                    LimparForm();
                }
            }).fail(function (data, status) {
                $.notify('Erro ao gravar os dados na tabela pessoa...', { clickToHide: true, autoHide: false });
                LimparForm();
            });
    }

    function CarregaWebCam() {
        $.ajax({
            url: '@Url.Action("WebCam", "Cadastro")',
            method: 'POST',
            dataType: 'html',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify({
                'acao': 'I'
            })
        }).done(function (data, status) {
            $('#divWebCam').html(data).show();
            $('.modal-title').html('Foto');
            $('#modalWebCam').modal();
        }).fail(function (data, status) {
            $.notify('Erro ao abrir a web cam...', { clickToHide: true, autoHide: false });
        });
    }

    $('#btnGravarNovaPessoa').click(function () {
        location.reload();
    });

</script>

}

GoedertWeb.UI/Views/Consulta/Index.cshtml
<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <h2>
                <label class="label label-info">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    Pesquisar
                </label>
            </h2>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4 form-group">
            <label for="pesquisarNome" class="control-label text-primary">Nome:</label>
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </span>
                <input id="pesquisarNome" type="text" placeholder="Digite o nome a buscar" class="form-control">                
            </div>
        </div>
        <div class="col-md-4 form-group">
            <label for="pesquisarDocumento" class="control-label text-primary">Documento:</label>
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </span>
                <input id="pesquisarDocumento" type="text" placeholder="Digite o número do documento" class="form-control">
            </div>
        </div>
        <div class="col-md-4 form-group">
            <label for="pesquisarUnidade" class="control-label text-primary">Unidade:</label>
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </span>
                <input id="pesquisarUnidade" type="text" placeholder="Digite a unidade" class="form-control">
            </div>
        </div>
    </div>
</div>

<div id="divResumoConsulta" style="display:none;">
</div>

<input id="idPessoa" type="hidden" value="">

@section scripts{

<script>    
    $(document).ready(function () {
        $('#pesquisarNome').autocomplete({            
            source: function (request, response) {
                $.ajax({
                    url: '@Session["WEB_API"].ToString()/api/pessoas/' + request.term + '/autoCompletePessoas',
                    method: 'GET',
                    dataType: 'json'
                }).done(function (data, status) {
                    response(data);
                }).fail(function (data, status) {
                    $.notify('Erro ao recuperar os dados para realizar o auto complete...', { clickToHide: true, autoHide: false });
                });
            },
            minLength: 3,
            select: function (event, ui) {
                GetPessoas(ui.item.label);
            }
        });

        $('#pesquisarDocumento').autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '@Session["WEB_API"].ToString()/api/documentos/' + request.term + '/autoCompleteDocumentos',
                    method: 'GET',
                    dataType: 'json'
                }).done(function (data, status) {
                    response(data);
                }).fail(function (data, status) {
                    $.notify('Erro ao recuperar os dados para realizar o auto complete...', { clickToHide: true, autoHide: false });
                });
            },
            minLength: 3,
            select: function (event, ui) {
                GetDocumentos(ui.item.label);
            }
        });
    });

</script>

}

<script>

    $(document).ready(function () {
        $('#pesquisarNome').autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '@Session["WEB_API"].ToString()/api/pessoas/' + request.term + '/autoCompletePessoas',
                    method: 'GET',
                    dataType: 'json'
                }).done(function (data, status) {
                    response(data);
                }).fail(function (data, status) {
                    $.notify('Erro ao recuperar os dados para realizar o auto complete...', { clickToHide: true, autoHide: false });
                });
            },
            minLength: 3,
            select: function (event, ui) {
                GetPessoas(ui.item.label);
            }
        });

        $('#pesquisarDocumento').autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '@Session["WEB_API"].ToString()/api/documentos/' + request.term + '/autoCompleteDocumentos',
                    method: 'GET',
                    dataType: 'json'
                }).done(function (data, status) {
                    response(data);
                }).fail(function (data, status) {
                    $.notify('Erro ao recuperar os dados para realizar o auto complete...', { clickToHide: true, autoHide: false });
                });
            },
            minLength: 3,
            select: function (event, ui) {
                GetDocumentos(ui.item.label);
            }
        });
    });

</script>

GoedertWeb.UI/Views/Home/Index.cshtml
@section scripts{
    <script>

    $(document).ready(function () {
        EntrarSite('S');
    });

    </script>
}

GoedertWeb.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <title>Goedert Web</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="bodyMain">
    <div class="navbar navbar-inverse navbar-fixed-top" id="divMenu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/img/controle_rapido_img_logo.png" alt="" style="padding-left:12px; padding-top:5px;" />                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Consulta")</li>
                    <li>@Html.ActionLink("Consulta", "Index", "Consulta")</li>
                    <li>@Html.ActionLink("Cadastro", "Index", "Cadastro")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container" id="divContainerMain" style="display:none;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="panel panel-entrar">
                        <div class="panel-body">
                            <div class="row row-centered">
                                <div class="col-lg-10 col-centered div-form-login">
                                    <div class="row">
                                        <div class="text-center img-logo-empresa">
                                            <img />
                                        </div>
                                    </div>
                                    <br />
                                    <div class="row">
                                        <div class="col-md-12 text-center">
                                            <span style="color: #2e9c45; padding-left:20%;">Bem vindo(a)!</span>
                                        </div>
                                    </div>
                                    <br />
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="button" id="btnEntrar" onclick="EntrarSite('N');" class="form-control btn btn-entrar" value="ENTRAR">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content" id="divRenderBody">
        @RenderBody()
        <div id="divConsulta" style="display:none;"></div>        
        <div class="row">
            <div class="col-md-12">
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Um produto Goedert Sistemas</p>
                    <p>Desenvolvido por Samuel Reis</p>
                    <p>Todos os direitos reservados</p>
                </footer>
            </div>
        </div>
    </div>

    <script>

        function EntrarSite(exibeTelaPrincipal) {
            if (exibeTelaPrincipal == 'N')
            {
                $('#bodyMain').removeClass('fundoBody');
                $('#divMenu').show();
                $('#divContainerMain').remove();                

                $.ajax({
                url: '@Url.Action("TelaConsulta", "Consulta")',
                method: 'POST',
                dataType: 'html',
                contentType: 'application/json; charset=utf-8'
                }).done(function (data, status) {
                    $('#divConsulta').html(data).show();                    
                }).fail(function (data, status) {
                    $.notify('Erro ao carregar a tela de consulta...', { clickToHide: true, autoHide: false });
                });                
            }
            else
            {
                $('#bodyMain').addClass('fundoBody');
                $('#divContainerMain').show();
                $('#divMenu').hide();                
                $('#divConsulta').hide();
            }
        }

        function GetPessoa(idPessoa) {
            $.ajax({
                url: '@Session["WEB_API"].ToString()/api/pessoas/' + idPessoa + '/listarPessoa',
                method: 'GET',
                dataType: 'json'
            }).done(function (data, status) {
                data = TrataJson(data);

                $.ajax({
                    url: '@Url.Action("ResumoConsulta", "Consulta")',
                    method: 'POST',
                    dataType: 'html',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({
                        'model': data,
                        'viewCadastro': 'S'
                    })
                }).done(function (data, status) {
                    $('#divResumoConsulta').html(data).show();
                    $('#divCadastro').remove();
                    $('#divBtnGravarNovaPessoa').show();
                }).fail(function (data, status) {
                    $.notify('Erro ao abrir a tela para listar a pessoa desejada...', { clickToHide: true, autoHide: false });
                });
            }).fail(function (data, status) {
                $.notify('Erro ao recuperar a pessoa desejada...', { clickToHide: true, autoHide: false });
            });
        }

        function GetPessoas(nome) {
            $.ajax({
                url: '@Session["WEB_API"].ToString()/api/pessoas/' + nome + '/listarPessoas',
                method: 'GET',
                dataType: 'json'
            }).done(function (data, status) {
                data = TrataJson(data);

                $.ajax({
                    url: '@Url.Action("ResumoConsulta", "Consulta")',
                    method: 'POST',
                    dataType: 'html',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({
                        'model': data,
                        'tipoPesquisa': 'N'
                    })
                }).done(function (data, status) {
                    $('#divResumoConsulta').html(data).show();
                }).fail(function (data, status) {
                    $.notify('Erro ao abrir a tela para listar a pessoa desejada...', { clickToHide: true, autoHide: false });
                });
            }).fail(function (data, status) {
                $.notify('Erro ao recuperar a pessoa desejada...', { clickToHide: true, autoHide: false });
            });
        }

        function GetDocumentos(numero) {
            $.ajax({
                url: '@Session["WEB_API"].ToString()/api/documentos/' + numero + '/listarDocumentos',
                method: 'GET',
                dataType: 'json'
            }).done(function (data, status) {
                $.each(data, function (i, item) {
                    var dadosPessoas = GetDadosPessoa(item.id_pessoa);
                    var dadosTipoPessoa = GetTipoPessoa(dadosPessoas.id_tipo_pessoa);
                    dadosPessoas = $.extend(dadosPessoas, { descricao: dadosTipoPessoa.descricao });

                    var dadosDocumentos = GetDocumento(item.id_pessoa);

                    if (dadosDocumentos.length > 0) {
                        var dadosTipoDocumento = {};
                        $.each(dadosDocumentos, function (idx, item) {
                            dadosTipoDocumento = GetTipoDocumento(item.id_tipo_documento);
                            dadosDocumentos[idx] = $.extend(dadosDocumentos[idx], { descricao: dadosTipoDocumento.descricao });
                        });
                    }

                    dadosDocumentos = { dadosDocumentos: dadosDocumentos };
                    data[i] = $.extend(dadosDocumentos, dadosPessoas);
                });

                 $.ajax({
                    url: '@Url.Action("ResumoConsulta", "Consulta")',
                    method: 'POST',
                    dataType: 'html',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({
                        'model': data,
                        'tipoPesquisa': 'D'
                    })
                }).done(function (data, status) {
                    $('#divResumoConsulta').html(data).show();
                }).fail(function (data, status) {
                    $.notify('Erro ao abrir a tela para listar a pessoa desejada...', { clickToHide: true, autoHide: false });
                });

            }).fail(function (data, status) {
                $.notify('Erro ao recuperar os documentos...', { clickToHide: true, autoHide: false });
            });
        }

        function TrataJson(data) {
            return $.each(data, function (i, item) {
                var dadosTipoPessoa = GetTipoPessoa(item.id_tipo_pessoa);
                data[i] = $.extend(data[i], { descricao: dadosTipoPessoa.descricao });

                var dadosDocumentos = GetDocumento(item.id_pessoa);
                if (dadosDocumentos.length > 0) {
                    var dadosTipoDocumento = {};
                    $.each(dadosDocumentos, function (idx, item) {
                        dadosTipoDocumento = GetTipoDocumento(item.id_tipo_documento);
                        dadosDocumentos[idx] = $.extend(dadosDocumentos[idx], { descricao: dadosTipoDocumento.descricao });
                    });
                }

                dadosDocumentos = { dadosDocumentos: dadosDocumentos };
                data[i] = $.extend(dadosDocumentos, data[i]);
            });
        }

        function GetDocumento(idPessoa) {
            return $.ajax({
                url: '@Session["WEB_API"].ToString()/api/documentos/' + idPessoa + '/listarDocumento',
                method: 'GET',
                dataType: 'json',
                async: false
            }).done(function (data, status) {
            }).fail(function (data, status) {
                $.notify('Erro ao recuperar o documento...', { clickToHide: true, autoHide: false });
            }).responseJSON;
        }

        function GetTipoPessoa(idTipoPessoa) {
            return $.ajax({
                url: '@Session["WEB_API"].ToString()/api/pessoas/' + idTipoPessoa + '/listarTipoPessoa',
                method: 'GET',
                dataType: 'json',
                async: false
            }).done(function (data, status) {
            }).fail(function (data, status) {
                $.notify('Erro ao recuperar o tipo de pessoa...', { clickToHide: true, autoHide: false });
            }).responseJSON[0];
        }

        function GetTipoDocumento(idTipoDocumento) {
            return $.ajax({
                url: '@Session["WEB_API"].ToString()/api/documentos/' + idTipoDocumento + '/listarTipoDocumento',
                method: 'GET',
                dataType: 'json',
                async: false
            }).done(function (data, status) {
            }).fail(function (data, status) {
                $.notify('Erro ao recuperar o tipo de documento...', { clickToHide: true, autoHide: false });
            }).responseJSON[0];
        }

        function GetDadosPessoa(idPessoa) {
            return $.ajax({
                url: '@Session["WEB_API"].ToString()/api/pessoas/' + idPessoa + '/listarPessoa',
                method: 'GET',
                dataType: 'json',
                async: false
            }).done(function (data, status) {
            }).fail(function (data, status) {
                $.notify('Erro ao recuperar a pessoa...', { clickToHide: true, autoHide: false });
            }).responseJSON[0];
        }

    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>